---
services:
  app:
    build:
      context: ../
      dockerfile: ./Dockerfile
#    network_mode: "host"
    volumes:
      - ../config:/config
      - ../logs:/logs
    env_file:
      - ../.env
    ports:
      - 8000:8000
