

permissions:
  roles:
    - title: user
      permissions:
        - demo.read
    - title: manager
      permissions:
        - demo.read
        - demo.write
    - title: admin
      permissions:
        - demo.read
        - demo.write
    - title: auditor
      permissions:
        - audit.read

  users:
    - username: demo_user_1
      roles:
        - user
    - username: demo_user_2
      roles:
        - admin
    - username: demo_user_3
      roles:
        - manager
        - auditor

log:
  console_format: "%(levelname)s | %(message)s"