

permissions:
  user:
    label: auth-demo-app-user
    permissions:
      - demo.read

  manager:
    label: auth-demo-app-manager
    permissions:
      - demo.read
      - demo.edit

  admin:
    label: auth-demo-app-admin
    permissions:
      - demo.read
      - demo.edit

  auditor:
    label: auth-demo-app-auditor
    permissions: []

log:
  console_format: "%(levelname)s | %(message)s"